name: setup gcloud

on:
  push:
    branches:
      - main

jobs:
  BuildDockerImage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          project_id: 'bootdev-cicd-507910'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Check gcloud
        run: |
          gcloud auth list
          gcloud config get-value project

      - name: Build Docker image
        run: |
          gcloud builds submit \
            --tag us-central1-docker.pkg.dev/bootdev-cicd-507910/notely-ar-repo/notely:latest \
            .